# Generated by Django 5.1.3 on 2024-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrestriction',
            name='label',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='version',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='section_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='section_order',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='processinglog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['restaurant', 'version'], name='menu_app_me_restaur_c88abf_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['section', 'name'], name='menu_app_me_section_79d9de_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['price', 'dietary_restriction'], name='menu_app_me_price_e796b3_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['menu', 'status'], name='menu_app_pr_menu_id_b09c34_idx'),
        ),
    ]
